# Generated by Django 5.0.3 on 2024-10-01 20:42

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('title_ru', models.CharField(max_length=250, null=True)),
                ('title_uz', models.CharField(max_length=250, null=True)),
                ('title_en', models.CharField(max_length=250, null=True)),
                ('image', models.FileField(upload_to='banner')),
                ('text', models.TextField()),
                ('text_ru', models.TextField(null=True)),
                ('text_uz', models.TextField(null=True)),
                ('text_en', models.TextField(null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Kasting Banner',
                'verbose_name_plural': 'Kasting Bannerlar',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Casting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_active', models.TextField()),
                ('text_active_ru', models.TextField(null=True)),
                ('text_active_uz', models.TextField(null=True)),
                ('text_active_en', models.TextField(null=True)),
                ('text_de_active', models.TextField()),
                ('text_de_active_ru', models.TextField(null=True)),
                ('text_de_active_uz', models.TextField(null=True)),
                ('text_de_active_en', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Kasting Yozuvi',
                'verbose_name_plural': 'Kasting Yozuvlari',
            },
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('title_ru', models.CharField(max_length=250, null=True)),
                ('title_uz', models.CharField(max_length=250, null=True)),
                ('title_en', models.CharField(max_length=250, null=True)),
                ('image', models.FileField(upload_to='main')),
                ('text', models.TextField()),
                ('text_ru', models.TextField(null=True)),
                ('text_uz', models.TextField(null=True)),
                ('text_en', models.TextField(null=True)),
                ('button_text', models.CharField(max_length=250)),
                ('button_text_ru', models.CharField(max_length=250, null=True)),
                ('button_text_uz', models.CharField(max_length=250, null=True)),
                ('button_text_en', models.CharField(max_length=250, null=True)),
                ('link', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Asosiy Sahifa Banneri',
                'verbose_name_plural': 'Asosiy Sahifa Bannerilari',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('name_ru', models.CharField(max_length=250, null=True)),
                ('name_uz', models.CharField(max_length=250, null=True)),
                ('name_en', models.CharField(max_length=250, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Mavsum',
                'verbose_name_plural': 'Mavsumlar',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('name_ru', models.CharField(max_length=250, null=True)),
                ('name_uz', models.CharField(max_length=250, null=True)),
                ('name_en', models.CharField(max_length=250, null=True)),
                ('main_page_image', models.FileField(upload_to='teachers/')),
                ('image', models.FileField(upload_to='teachers')),
                ('bio', ckeditor.fields.RichTextField()),
                ('bio_ru', ckeditor.fields.RichTextField(null=True)),
                ('bio_uz', ckeditor.fields.RichTextField(null=True)),
                ('bio_en', ckeditor.fields.RichTextField(null=True)),
                ('facebook_link', models.CharField(blank=True, max_length=250, null=True)),
                ('instagram_link', models.CharField(blank=True, max_length=250, null=True)),
                ('twitter_link', models.CharField(blank=True, max_length=250, null=True)),
                ('youtube_link', models.CharField(blank=True, max_length=250, null=True)),
                ('telegram_link', models.CharField(blank=True, max_length=250, null=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='kids.season')),
            ],
            options={
                'verbose_name': 'Uztoz',
                'verbose_name_plural': 'Uztozlar',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('name_ru', models.CharField(max_length=250, null=True)),
                ('name_uz', models.CharField(max_length=250, null=True)),
                ('name_en', models.CharField(max_length=250, null=True)),
                ('image', models.FileField(upload_to='participants')),
                ('bio', ckeditor.fields.RichTextField()),
                ('bio_ru', ckeditor.fields.RichTextField(null=True)),
                ('bio_uz', ckeditor.fields.RichTextField(null=True)),
                ('bio_en', ckeditor.fields.RichTextField(null=True)),
                ('facebook_link', models.CharField(blank=True, max_length=250, null=True)),
                ('instagram_link', models.CharField(blank=True, max_length=250, null=True)),
                ('twitter_link', models.CharField(blank=True, max_length=250, null=True)),
                ('youtube_link', models.CharField(blank=True, max_length=250, null=True)),
                ('telegram_link', models.CharField(blank=True, max_length=250, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='kids.season')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='kids.teacher')),
            ],
            options={
                'verbose_name': 'Ishtirokchi',
                'verbose_name_plural': 'Ishtirokchilar',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='VoiceTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_times', to='kids.season')),
            ],
            options={
                'verbose_name': 'Ovoz berish Vaqti',
                'verbose_name_plural': 'Ovoz berish Vaqtlari',
            },
        ),
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('title_ru', models.CharField(max_length=250, null=True)),
                ('title_uz', models.CharField(max_length=250, null=True)),
                ('title_en', models.CharField(max_length=250, null=True)),
                ('image', models.FileField(upload_to='winner')),
                ('blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kids_winners', to='blog.blog')),
            ],
            options={
                'verbose_name': "G'olib",
                'verbose_name_plural': "G'oliblar",
            },
        ),
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=250)),
                ('singer_name', models.CharField(max_length=250)),
                ('link', models.URLField()),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='youtube_videos', to='kids.season')),
            ],
            options={
                'verbose_name': 'YouTube Video',
                'verbose_name_plural': 'YouTube Videolari',
                'ordering': ['-id'],
            },
        ),
    ]
