# Generated by Django 5.0.3 on 2024-10-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(upload_to='partners')),
                ('link', models.URLField(max_length=350)),
            ],
            options={
                'verbose_name': 'Partnor',
                'verbose_name_plural': 'Partnorlar',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(upload_to='sponsors')),
                ('link', models.URLField(max_length=350)),
            ],
            options={
                'verbose_name': 'Homiy',
                'verbose_name_plural': 'Homiylar',
                'ordering': ['id'],
            },
        ),
    ]
