# Generated by Django 5.0.3 on 2024-10-01 20:42

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('title_ru', models.CharField(max_length=150, null=True)),
                ('title_uz', models.CharField(max_length=150, null=True)),
                ('title_en', models.CharField(max_length=150, null=True)),
                ('image', models.FileField(upload_to='blog/')),
                ('content', ckeditor.fields.RichTextField()),
                ('content_ru', ckeditor.fields.RichTextField(null=True)),
                ('content_uz', ckeditor.fields.RichTextField(null=True)),
                ('content_en', ckeditor.fields.RichTextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Bloglar',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=250)),
                ('singer_name', models.CharField(max_length=250)),
                ('link', models.URLField()),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='youtube_videos', to='main.season')),
            ],
            options={
                'verbose_name': 'YouTube Video',
                'verbose_name_plural': 'YouTube Videolari',
                'ordering': ['-id'],
            },
        ),
    ]
